# ----------------------------------------------- #
# Note: this file originates in template-node-lib #
# ----------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

permissions: read-all

jobs:
  main:
    uses: khulnasoft/actions/.github/workflows/push-javascript.yml@master
    secrets: inherit
    permissions:
      contents: write
      statuses: write
      packages: write
      pull-requests: write
